const actionTypes = {
  LOAD_MOVIES: 'LOAD_MOVIES',
  LOAD_MOVIES_ERROR: 'LOAD_MOVIES_ERROR',
  LOAD_SELECTED_MOVIE: 'LOAD_SELECTED_MOVIE',
  
  LOAD_TVSHOWS: 'LOAD_TVSHOWS',
  LOAD_TVSHOWS_ERROR: 'LOAD_TVSHOWS_ERROR',
};

export default actionTypes;
