const actionTypes = {
  LOAD_MOVIES: 'LOAD_MOVIES',
  LOAD_MOVIES_ERROR: 'LOAD_MOVIES_ERROR',
  
  LOAD_TVSHOWS: 'LOAD_TVSHOWS',
  LOAD_TVSHOWS_ERROR: 'LOAD_TVSHOWS_ERROR',

  LOAD_SIMILAR_TITLES: 'LOAD_SIMILAR_TITLES',
  LOAD_SIMILAR_TITLES_ERROR: 'LOAD_SIMILAR_TITLES_ERROR',

  LOAD_DETAILS:'LOAD_DETAILS',
  LOAD_DETAILS_ERROR: 'LOAD_DETAILS_ERROR'
};

export default actionTypes;
